---
Author: "Jiacheng Zhu"
title: "HW2-JiachengZhu"
output: html_document
---
```{r,include=FALSE}

library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(scales)
library(ggbeeswarm)

load("/Users/JZHU/hwk-2-JiachengZ98/HCRIS.Workspace.RData")
```

```{r}
final.hcris.v1996 %>% filter(year == 2010) %>% count()
```
Hospitals have different fiscal years. 

```{r}
duplicate <- duplicate.hcris %>% ungroup() %>% group_by(fyear) %>% summarise(count=n())
ggplot(data=duplicate, aes(x=fyear, y=count, group=1)) +
  geom_line(aes(group=1))+
  theme_bw()
```

```{r,warning=FALSE} 
final.hcris.data <- final.hcris.data %>% group_by(year) %>% mutate(count.hospitals =n())
final.hcris.data %>% 
  ggplot(aes(x=as.factor(year), y=count.hospitals)) +
  geom_line(aes(group=1))+
  labs(
    x="Year",
    y="Number of Hospitals",
    title="Number of Hospitals per Year"
  ) +
  theme_bw()
```


```{r,warning=FALSE}
quantile(final.hcris.data$tot_charges,c(.01,.99),na.rm = TRUE)

final.hcris.data %>% mutate(tot_charges_low=quantile(tot_charges, probs=0.01, na.rm=TRUE),
            tot_charges_high=quantile(tot_charges, probs=0.99, na.rm=TRUE)) %>%
  filter(tot_charges<tot_charges_high, tot_charges>tot_charges_low,
         !is.na(tot_charges), year>1997) %>%
  mutate(log_tot_charges=log(tot_charges))%>%
  ggplot(aes(x= year, y= log_tot_charges)) +
  geom_quasirandom(alpha = 0.05, width = 0.1)+  
  stat_summary(fun.y = "median", geom = "point", size = 2,color = "#abdcf1") +
  stat_summary(fun.y = "median", geom = "line", aes(group = 1),size = 1.1,color = "#abdcf1")+
   scale_y_continuous(limits = c(15,23),
                     expand = c(0,0))

```


```{r,warning=FALSE}
final.hcris.data <- final.hcris.data %>% 
  mutate(discount_factor = 1-tot_discounts/tot_charges, 
  price_num = (ip_charges + icu_charges + ancillary_charges)*discount_factor - tot_mcare_payment,
  price_denom = tot_discharges - mcare_discharges, 
  price = price_num/price_denom) %>%   
  filter(price_denom>100, !is.na(price_denom), 
         price_num>0, !is.na(price_num),
         price<100000, 
         beds>30)

final.hcris.data %>% 
  ggplot(aes(x = year, y = price)) +
  geom_quasirandom(alpha = 0.05, width = 0.1)+
  stat_summary(fun.y = "median", geom = "point", size = 2) +
  stat_summary(fun.y = "median", geom = "line", aes(group = 1),
               size = 1.1) +
  scale_y_continuous(limits = c(-3000,50000),
                     expand = c(0,0),
                     labels = scales::unit_format(unit = "$"))  

```

```{r,warning=FALSE}

final.hcris.data <- final.hcris.data %>% 
  mutate(hvbp_payment = ifelse(is.na(hvbp_payment),0,hvbp_payment),
          hrrp_payment = ifelse(is.na(hrrp_payment),0,abs(hrrp_payment)))%>%
  mutate(penalized = case_when(
  hrrp_payment > 0~1,
))

final.hcris.data %>% ungroup %>% group_by(year,penalized) %>% filter(!is.na(penalized)) %>%   
            mutate(count.penalized = n(), penalized.share = count.penalized / count.hospitals) %>%
  ggplot(aes(x=as.factor(year), y= penalized.share))+
  geom_line(aes(group=1)) +
  theme_bw()

```


```{r}
final.hcris.data <- final.hcris.data %>% mutate(penalty = as.numeric((hvbp_payment - hrrp_payment <0)))

final.hcris.data.2012 <- final.hcris.data %>% select(-penalized,-price_denom,-price_num,-discount_factor) %>% filter(year == 2012)

final.hcris.data.2012 %>% group_by(penalty) %>% summarise(mean_price =mean(price))

final.hcris.data.2012 %>% filter(penalty == TRUE) %>% summarise(mean.penalized = mean(price))
final.hcris.data.2012 %>% filter(penalty == FALSE) %>% summarise(mean.unpenalized = mean(price))
```

```{r}
quantile(final.hcris.data.2012$beds,c(.25,.5,.75),na.rm = TRUE)

final.hcris.data.2012 <- final.hcris.data.2012 %>%ungroup() %>%
  mutate(beds_q1 = quantile(beds, probs=0.25, na.rm=TRUE),
         beds_q2 = quantile(beds, probs=0.50, na.rm=TRUE),
         beds_q3 = quantile(beds, probs=0.75, na.rm=TRUE),
         beds_q4 = max(beds, na.rm=TRUE)) %>%
  mutate(quartile.1 = ifelse(beds<beds_q1,1,0),
         quartile.2 = ifelse(beds>= beds_q1 & beds<beds_q2,1,0),
         quartile.3 = ifelse(beds>= beds_q2 & beds<beds_q3,1,0),
         quartile.4 = ifelse(beds>= beds_q3 & beds<beds_q4,1,0))
```

```{r}
match.inv <- Matching::Match(Y=final.hcris.data.2012$price,
                Tr=final.hcris.data.2012$penalty,
                X= (final.hcris.data.2012 %>% select(quartile.1, quartile.2, quartile.3)),
                M=1,
                Weight=1,
                estimand="ATE",
                ties=FALSE)

summary(match.inv)

```
```{r}
match.mah <- Matching::Match(Y=final.hcris.data.2012$price,
                Tr=final.hcris.data.2012$penalty,
                X= (final.hcris.data.2012 %>% select(quartile.1, quartile.2, quartile.3)),
                M=1,
                Weight=2,
                estimand="ATE",
                ties=FALSE)
summary(match.mah)
```

```{r}
logit.model <- glm(penalty ~ quartile.1 + quartile.2 + quartile.3, 
                   family=binomial, 
                   data=final.hcris.data.2012)
ps <- fitted(logit.model)

final.hcris.data.2012 <- final.hcris.data.2012 %>%
  mutate(ipw = case_when(
    penalty==1 ~ 1/ps,
    penalty==0 ~ 1/(1-ps),
    TRUE ~ NA_real_
  ))
```


```{r}
mean.t1 <- final.hcris.data.2012 %>% filter(penalty==TRUE) %>%
  select(price, ipw) %>% summarize(mean_p=weighted.mean(price,w=ipw))
mean.t0 <- final.hcris.data.2012 %>% filter(penalty==FALSE) %>%
  select(price, ipw) %>% summarize(mean_p=weighted.mean(price,w=ipw))

ipw.diff <- mean.t1$mean_p - mean.t0$mean_p
ipw.reg <- lm(price ~ penalty, data=final.hcris.data.2012, weights=ipw)

summary(ipw.reg)
```

```{r}
reg.data <- final.hcris.data.2012 %>% ungroup() %>%
  mutate(size1_diff = penalty*(quartile.1 - mean(quartile.1)),
         size2_diff = penalty*(quartile.2 - mean(quartile.2)),
         size3_diff = penalty*(quartile.3 - mean(quartile.3)))

reg <- lm(price ~ penalty + quartile.1 + quartile.2 + quartile.3 +
            size1_diff + size2_diff + size3_diff,
          data=reg.data)

summary(reg)
```
